### ISSUE TITLE
Query: Is there a way to specify different Common Name to issue certs using Cert Manager

### ISSUE THREAD

**Issue by sbhaita** [knative-extensions/net-certmanager#519]
We need to provide an ability to specify a different common name for our certs using AutoTLS in our Knative clusters. Is this possible in net-certmanager ? We are using Venafi as our Cert issuer and support for different/alternative CN is available here

How do we accomplish this in Knative using net-certmanager??

**Comment by dprotaso** [comment]
Curious what's the use case to specify a different Common Name?
