### ISSUE TITLE
Bump cert manager to v1.13

### ISSUE THREAD

**Issue by dprotaso** [knative-extensions/net-certmanager#588]
We're on a super old version - we should be bumping to the latest

https://github.com/cert-manager/cert-manager

**Comment by Priyansurout** [comment]
Could you please assign this issue to me? I am eager to dive in and start working on it.

**Comment by ReToCode** [comment]
Hm:
```
# for 1.13.0
go: github.com/cert-manager/cert-manager@v1.13.0 requires k8s.io/api@v0.28.1, not k8s.io/api@v0.26.9

# for 1.12.x
go: github.com/cert-manager/cert-manager@v1.12.4 requires k8s.io/api@v0.27.2, not k8s.io/api@v0.26.9
````

So we can only bump it to 1.11.x, let's see in https://github.com/knative-extensions/net-certmanager/pull/595

**Comment by dprotaso** [comment]
We can do `replace` rules in the go mod file to pin the k8s deps

**Comment by nak3** [comment]
`replace` rule will cause as https://github.com/knative-extensions/net-certmanager/pull/598
