### ISSUE TITLE
Release tested cert-manager's manifests `cert-manager.yaml` 

### ISSUE THREAD

**Issue by nak3** [knative-extensions/net-certmanager#596]
As per title, currently release manifests do not have the `cert-manager.yaml` as [releases/tag/knative-v1.11.1](https://github.com/knative-extensions/net-certmanager/releases/tag/knative-v1.11.1)

Other net-* plugins like [net-contour](https://github.com/knative-extensions/net-contour/releases/tag/knative-v1.11.1) and [net-istio](https://github.com/knative-extensions/net-istio/releases/tag/knative-v1.11.0) includes the tested yaml. It makes users use easier.

Also, we can add it to bot to sync to serving repo for test:

https://github.com/knative-extensions/knobots/blob/9a95f1f863feff2231e07a3912a37c4e0210c506/.github/workflows/update-nightlies.yaml#L48-L51

instead of bumping the manifest on Serving side like https://github.com/knative/serving/issues/14383

**Comment by dprotaso** [comment]
Closing this out in favour of https://github.com/knative/serving/issues/14740
